export default [
  'strapi::logger',
  'strapi::errors',
  'strapi::security',
  { resolve: './src/middlewares/db-switch' },
  { resolve: './src/middlewares/tenant' },
  { resolve: './src/middlewares/tenant-filter' },
  'strapi::cors',
  'strapi::poweredBy',
  'strapi::query',
  'strapi::body',
  'strapi::session',
  'strapi::favicon',
  'strapi::public',
];
